import type {
  Competition
} from "../../types/models";

export const sampleCompetitions: Competition[] = [
  {
    id: "lct",
    event_id: "games-2026",
    name: "Lomba Cepat Tepat Matematika",
    slug: "lct-matematika",
    code: "LCT",
    short_description: "Kompetisi cepat dan tepat menyelesaikan soal matematika secara tim.",
    description: "LCT Matematika menguji kemampuan kognitif, pemecahan masalah, kerja sama, dan kecepatan berpikir.",
    participant_levels: ["SD", "SMP", "SMA"],
    competition_type: "team",
    min_members: 2,
    max_members: 3,
    registration_fee: 0,
    registration_status: "open",
    registration_open_at: null,
    registration_close_at: null,
    guidebook_url: null,
    poster_url: null,
    contact_person: null,
    whatsapp_cp: null,
    is_active: true,
  },
  {
    id: "olim",
    event_id: "games-2026",
    name: "Olimpiade Matematika",
    slug: "olimpiade-matematika",
    code: "OLIM",
    short_description: "Kompetisi pemecahan soal matematika menantang untuk siswa.",
    description: "Olimpiade Matematika menguji kemampuan problem solving dan penalaran matematis peserta.",
    participant_levels: ["SD", "SMP", "SMA"],
    competition_type: "individual",
    min_members: 1,
    max_members: 1,
    registration_fee: 0,
    registration_status: "open",
    registration_open_at: null,
    registration_close_at: null,
    guidebook_url: null,
    poster_url: null,
    contact_person: null,
    whatsapp_cp: null,
    is_active: true,
  },
  {
    id: "ranking-1",
    event_id: "games-2026",
    name: "Ranking 1",
    slug: "ranking-1",
    code: "R1",
    short_description: "Adu ketepatan menjawab pertanyaan hingga tersisa satu pemenang.",
    description: "Ranking 1 ditujukan untuk siswa SD/sederajat dengan format eliminasi bertahap.",
    participant_levels: ["SD"],
    competition_type: "individual",
    min_members: 1,
    max_members: 1,
    registration_fee: 0,
    registration_status: "open",
    registration_open_at: null,
    registration_close_at: null,
    guidebook_url: null,
    poster_url: null,
    contact_person: null,
    whatsapp_cp: null,
    is_active: true,
  },
];